Working BioPage with basic Calendar
BoostPT/boostPT-ui pull request #23
Opened 2018-05-17 23:12 UTC by DChan0319

2018-05-17 23:16 UTC, zgallagher08 commented on client/src/actions/index.js
> +    const signedUrl = await axios.post('http://localhost:8000/api/aws/s3',picture);
add cookie to headers

2018-05-17 23:16 UTC, zgallagher08 commented on client/src/actions/index.js
> +    await axios.put(signedUrl.data, payload.file[0], options);
add cookie to header

2018-05-17 23:16 UTC, amelendez37 commented on client/src/actions/index.js
> +        let exercises = await axios.get(`http://localhost:8000/api/workouts/exercises/${publicWorkout.id}`);
put header for cookie

2018-05-17 23:19 UTC, amelendez37 approved these changes

2018-05-17 23:19 UTC, zgallagher08 commented on client/src/components/workoutsView/workoutItem.jsx
> +      {!this.props.clickedWorkout ? null :
copy/paste this file from github, no need to fix.

2018-05-17 23:23 UTC, zgallagher08 commented on client/src/containers/workoutItemContainer.jsx
> +       star={!this.props.clickedWorkout? false : !!this.props.clickedWorkout.star}
just change this to star={star}

2018-05-17 23:26 UTC, zgallagher08 requested changes
see comments

2018-05-18 00:12 UTC, DChan0319 commented
workoutItem.jsx doesn't work with current master version for the  hitting the BioPage. Works with my version though.

2018-05-18 00:19 UTC, zgallagher08 approved these changes

2018-05-18 00:19 UTC, merged