Calendar
BoostPT/boostPT-ui pull request #30
Opened 2018-05-21 21:43 UTC by DChan0319

2018-05-21 21:52 UTC, DChan0319 commented
Not sure why it says i have conflicting files to be automatically merged.

2018-05-22 18:49 UTC, zgallagher08 commented on client/src/components/dashPage/workoutsTab.jsx
> +  starRerenderfunction(){
can you delete this empty function?

2018-05-22 18:49 UTC, zgallagher08 commented on client/src/components/dashPage/workoutsTab.jsx
> +        <WorkoutItemContainer starRerenderfunction={this.starRerenderfunction}/>
also delete the empty prop from here

2018-05-22 18:56 UTC, zgallagher08 requested changes
Awesome. One very small change, just delete that function

2018-05-22 23:10 UTC, zgallagher08 approved these changes

2018-05-22 23:14 UTC, jaba9531 approved these changes
Nice work

2018-05-22 23:55 UTC, amelendez37 approved these changes

2018-05-22 23:55 UTC, merged